# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd860541264cf5e9325ef76bd6fb3df5cd31cdde58419e515c6dd6c2eda855a2f78d4e2c9ca5d7255a49564e1e456cbf7150806a5e70752047798a3ccfae9a9a

test:
  secret_key_base: 67407309e7d0ae0487f2ef7e20fa2f43f31c2f76b3dcc911773bbe6641586e373c9f8e75e57bba4993e76ab8f0684f6a843b3b0dcfbaf8f41a51648bd2ea47af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
